version: '3'
services:
  app:
    image: envios

    container_name: envios

    build: .
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 250M
        reservations:
          cpus: "0.25"
          memory: 128M
    command: node .
    links:
      - mongo
    ports:
      - 3000:3000


  mongo:
    image: mongo:3.6
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Compass
    # ports:
    # - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: envios
      MONGO_INITDB_ROOT_PASSWORD: envios
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./postales.agz:/postales
volumes:
  mongo:
